### ISSUE TITLE
Errors showing in console view. These are shown on first loading the website. Error 4. 

### ISSUE THREAD

**Issue by Patrick-Frendo** [Dame2Dolla/TechyDev#8]
![image](https://user-images.githubusercontent.com/16851267/221425763-c069e93e-dfa4-4a54-ba31-df6ad1a6b676.png)

**Forth error:** Failed to load resource: the server responded with a status of 404 ()

**Comment by Qlify** [comment]
Fixed the issue :D

**Comment by Patrick-Frendo** [comment]
> Fixed the issue :D

I can still see the error message, what did you do as a fix?

**Comment by Patrick-Frendo** [comment]
Also i just noticed this issue is the same as issue [number 6](https://github.com/Dame2Dolla/TechyDev/issues/6). This issue will be closed. Please any update go to [Issue 6](https://github.com/Dame2Dolla/TechyDev/issues/6). :)
